#修改当前程序的端口号
server:
  port: 8001
#加载mybatis的配置文件和映射文件
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  #给实体类取别名
  type-aliases-package: com.springcloud.entities
  #加载MyBatis的映射文件
  mapper-locations: mybatis/mapper/**/*.xml
#当前微服务取别名
spring:
  application:
    name: biemingApp
#配置连接数据库的信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 6789

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/		#集群版
  instance:
    instance-id: SpringCloud_8001 #给当前服务取别名
    prefer-ip-address: true #可以将微服务别名对应到具体的IP地址

info:
  app.name: SpingCloud_8001
  company.name: www.8001.com
  build.artifactId: microservicecloud_provider
  build.version: 1.0-SNAPSHOT
